{{- if .Values.portal.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portal
  namespace: {{ include "buildbarn.namespace" . }}
  labels:
    {{- include "buildbarn.labels" . | nindent 4 }}
spec:
  {{- if .Values.portal.ingress.ingressClassName }}
  ingressClassName: {{ .Values.portal.ingress.ingressClassName }}
  {{- end }}
  rules:
  - host: {{ .Values.portal.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: portal
            port:
              name: http
{{- end }}
