apiVersion: v1
kind: ConfigMap
metadata:
  name: buildbarn-config
  namespace: {{ include "buildbarn.namespace" . }}
  labels:
    {{- include "buildbarn.labels" . | nindent 4 }}
data:
  common.libsonnet: |
    {
      blobstore: {
        contentAddressableStorage: {
          sharding: {
            shards: {{ include "buildbarn.storageShards" . | nindent 12 }},
          },
        },
        actionCache: {
          completenessChecking: {
            backend: {
              sharding: {
                shards: {{ include "buildbarn.storageShards" . | nindent 16 }},
              },
            },
            maximumTotalTreeSizeBytes: 64 * 1024 * 1024,
          },
        },
      },
      fileSystemAccessCache: {
        sharding: {
          shards: {{ include "buildbarn.storageShards" . | nindent 10 }},
        },
      },
      browserUrl: 'http://bb-browser.example.com:80',
      maximumMessageSizeBytes: {{ .Values.global.maximumMessageSizeBytes | int64 }},
      global: {
        diagnosticsHttpServer: {
          httpServers: [{
            listenAddresses: [':9980'],
            authenticationPolicy: { allow: {} },
          }],
          enablePrometheus: true,
          enablePprof: true,
          enableActiveSpans: true,
        },
      },
    }
  storage.jsonnet: |
    local common = import 'common.libsonnet';

    {
      grpcServers: [{
        listenAddresses: [':8981'],
        authenticationPolicy: { allow: {} },
      }],
      maximumMessageSizeBytes: common.maximumMessageSizeBytes,
      global: common.global,
      contentAddressableStorage: {
        backend: {
          'local': {
            keyLocationMapOnBlockDevice: {
              file: {
                path: '/storage-cas/key_location_map',
                sizeBytes: {{ .Values.storage.cas.keyLocationMapSizeBytes | int64 }},
              },
            },
            keyLocationMapMaximumGetAttempts: 16,
            keyLocationMapMaximumPutAttempts: 64,
            oldBlocks: 8,
            currentBlocks: 24,
            newBlocks: 3,
            blocksOnBlockDevice: {
              source: {
                file: {
                  path: '/storage-cas/blocks',
                  sizeBytes: {{ .Values.storage.cas.blockSizeBytes | int64 }},
                },
              },
              spareBlocks: 3,
            },
            persistent: {
              stateDirectoryPath: '/storage-cas/persistent_state',
              minimumEpochInterval: '300s',
            },
          },
        },
        getAuthorizer: { allow: {} },
        putAuthorizer: { allow: {} },
        findMissingAuthorizer: { allow: {} },
      },
      actionCache: {
        backend: {
          'local': {
            keyLocationMapOnBlockDevice: {
              file: {
                path: '/storage-ac/key_location_map',
                sizeBytes: {{ .Values.storage.ac.keyLocationMapSizeBytes | int64 }},
              },
            },
            keyLocationMapMaximumGetAttempts: 16,
            keyLocationMapMaximumPutAttempts: 64,
            oldBlocks: 8,
            currentBlocks: 24,
            newBlocks: 1,
            blocksOnBlockDevice: {
              source: {
                file: {
                  path: '/storage-ac/blocks',
                  sizeBytes: {{ .Values.storage.ac.blockSizeBytes | int64 }},
                },
              },
              spareBlocks: 3,
            },
            persistent: {
              stateDirectoryPath: '/storage-ac/persistent_state',
              minimumEpochInterval: '300s',
            },
          },
        },
        getAuthorizer: { allow: {} },
        putAuthorizer: { allow: {} },
      },
      fileSystemAccessCache: {
        backend: {
          'local': {
            keyLocationMapOnBlockDevice: {
              file: {
                path: '/storage-fsac/key_location_map',
                sizeBytes: {{ .Values.storage.fsac.keyLocationMapSizeBytes | int64 }},
              },
            },
            keyLocationMapMaximumGetAttempts: 16,
            keyLocationMapMaximumPutAttempts: 64,
            oldBlocks: 8,
            currentBlocks: 24,
            newBlocks: 1,
            blocksOnBlockDevice: {
              source: {
                file: {
                  path: '/storage-fsac/blocks',
                  sizeBytes: {{ .Values.storage.fsac.blockSizeBytes | int64 }},
                },
              },
              spareBlocks: 3,
            },
            persistent: {
              stateDirectoryPath: '/storage-fsac/persistent_state',
              minimumEpochInterval: '300s',
            },
          },
        },
        getAuthorizer: { allow: {} },
        putAuthorizer: { allow: {} },
      },
    }
  frontend.jsonnet: |
    local common = import 'common.libsonnet';

    {
      grpcServers: [{
        listenAddresses: [':8980'],
        authenticationPolicy: { allow: {} },
      }],
      schedulers: {
        '': {
          endpoint: {
            address: 'scheduler:8982',
            addMetadataJmespathExpression: {
              expression: |||
                {
                  "build.bazel.remote.execution.v2.requestmetadata-bin": incomingGRPCMetadata."build.bazel.remote.execution.v2.requestmetadata-bin"
                }
              |||,
            },
          },
        },
      },
      maximumMessageSizeBytes: common.maximumMessageSizeBytes,
      global: common.global,
      contentAddressableStorage: {
        backend: common.blobstore.contentAddressableStorage,
        getAuthorizer: { allow: {} },
        putAuthorizer: { allow: {} },
        findMissingAuthorizer: { allow: {} },
      },
      actionCache: {
        backend: common.blobstore.actionCache,
        getAuthorizer: { allow: {} },
        putAuthorizer: { allow: {} },
      },
      fileSystemAccessCache: {
        backend: common.fileSystemAccessCache,
        getAuthorizer: { allow: {} },
        putAuthorizer: { allow: {} },
      },
      executeAuthorizer: { allow: {} },
    }
