{{- if not .Values.postgres.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "buildbarn.postgresSecretName" . }}
  namespace: {{ include "buildbarn.namespace" . }}
  labels:
    {{- include "buildbarn.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.postgres.password | quote }}
{{- end }}
